### ISSUE TITLE
Install Error on Windows

### ISSUE THREAD

**Issue by bbehling** [apollostack/GitHunt-angular2#52]
**I am recieving this error on a windows box when installing**

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.21 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer string-replace-loader@1.0.3 wants webpack@1.x.x || 2.x.x
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.0 wants webpack@^2.1.0-beta

npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp\githuntdemo\GitHunt-angular2\npm-debug.log

**Heres the output from the log:**

1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose readDependencies loading dependencies from C:\temp\githuntdemo\GitHunt-angular2\package.json
5 verbose install where, deps [ 'C:\\temp\\githuntdemo\\GitHunt-angular2',
5 verbose install   [ '@angular/common',
5 verbose install     '@angular/compiler',
5 verbose install     '@angular/core',
5 verbose install     '@angular/forms',
5 verbose install     '@angular/http',
5 verbose install     '@angular/platform-browser',
5 verbose install     '@angular/platform-browser-dynamic',
5 verbose install     '@angular/router',
5 verbose install     'angular2-apollo',
5 verbose install     'angular2-moment',
5 verbose install     'apollo-client',
5 verbose install     'core-js',
5 verbose install     'node-emoji',
5 verbose install     'rxjs',
5 verbose install     'ts-helpers',
5 verbose install     'zone.js',
5 verbose install     '@types/isomorphic-fetch',
5 verbose install     '@types/jasmine',
5 verbose install     '@types/node',
5 verbose install     'angular-cli',
5 verbose install     'codelyzer',
5 verbose install     'ts-node',
5 verbose install     'tslint',
5 verbose install     'typed-graphql',
5 verbose install     'typescript' ] ]
6 verbose install where, peers [ 'C:\\temp\\githuntdemo\\GitHunt-angular2', [] ]
7 verbose installManyTop reading for lifecycle C:\temp\githuntdemo\GitHunt-angular2\package.json
8 info preinstall githunt@0.0.0
9 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli
\package.json
10 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular2-a
pollo\package.json
11 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular2-m
oment\package.json
12 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\apollo-cli
ent\package.json
13 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\codelyzer\
package.json
14 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\core-js\pa
ckage.json
15 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\node-emoji
\package.json
16 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\rxjs\packa
ge.json
17 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\ts-helpers
\package.json
18 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\ts-node\pa
ckage.json
19 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\tslint\pac
kage.json
20 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\typed-grap
hql\package.json
21 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\typescript
\package.json
22 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\zone.js\pa
ckage.json
23 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@types\iso
morphic-fetch\package.json
24 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@types\jas
mine\package.json
25 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@types\nod
e\package.json
26 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\c
ommon\package.json
27 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\c
ompiler\package.json
28 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\c
ore\package.json
29 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\f
orms\package.json
30 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\h
ttp\package.json
31 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\p
latform-browser\package.json
32 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\p
latform-browser-dynamic\package.json
33 verbose installManyTop reading scoped package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\r
outer\package.json
34 info package.json ts-node@1.2.1 No README data
35 verbose readDependencies loading dependencies from C:\temp\githuntdemo\GitHunt-angular2\package.json
36 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\packa
ge.json
37 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular2-apollo\p
ackage.json
38 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular2-moment\p
ackage.json
39 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\apollo-client\pac
kage.json
40 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\codelyzer\package
.json
41 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\core-js\package.j
son
42 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\node-emoji\packag
e.json
43 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\rxjs\package.json
44 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\ts-helpers\packag
e.json
45 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\ts-node\package.j
son
46 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\tslint\package.js
on
47 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\typed-graphql\pac
kage.json
48 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\typescript\packag
e.json
49 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\zone.js\package.j
son
50 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\common\p
ackage.json
51 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\compiler
\package.json
52 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\core\pac
kage.json
53 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\forms\pa
ckage.json
54 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\http\pac
kage.json
55 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\platform
-browser\package.json
56 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\platform
-browser-dynamic\package.json
57 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@angular\router\p
ackage.json
58 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\.bin\ng\package.j
son
59 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\.bin\ng.cmd\packa
ge.json
60 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\.bin\ts-node\pack
age.json
61 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\.bin\ts-node.cmd\
package.json
62 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\.bin\tsc\package.
json
63 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\.bin\tsc.cmd\pack
age.json
64 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\.bin\tslint\packa
ge.json
65 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\.bin\tslint.cmd\p
ackage.json
66 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\.bin\tsserver\pac
kage.json
67 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\.bin\tsserver.cmd
\package.json
68 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@types\isomorphic
-fetch\package.json
69 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@types\jasmine\pa
ckage.json
70 verbose targetResolver reading package data from C:\temp\githuntdemo\GitHunt-angular2\node_modules\@types\node\packa
ge.json
71 verbose already installed skipping @angular/platform-browser-dynamic@2.0.0 C:\temp\githuntdemo\GitHunt-angular2
72 verbose already installed skipping @angular/router@3.0.0 C:\temp\githuntdemo\GitHunt-angular2
73 verbose already installed skipping angular2-apollo@^0.4.6 C:\temp\githuntdemo\GitHunt-angular2
74 verbose already installed skipping angular2-moment@^1.0.0-beta.1 C:\temp\githuntdemo\GitHunt-angular2
75 verbose already installed skipping apollo-client@^0.4.15 C:\temp\githuntdemo\GitHunt-angular2
76 verbose already installed skipping core-js@^2.4.0 C:\temp\githuntdemo\GitHunt-angular2
77 verbose already installed skipping node-emoji@^1.3.1 C:\temp\githuntdemo\GitHunt-angular2
78 verbose already installed skipping rxjs@5.0.0-beta.12 C:\temp\githuntdemo\GitHunt-angular2
79 verbose already installed skipping ts-helpers@^1.1.1 C:\temp\githuntdemo\GitHunt-angular2
80 verbose already installed skipping zone.js@^0.6.23 C:\temp\githuntdemo\GitHunt-angular2
81 verbose already installed skipping @types/isomorphic-fetch@0.0.30 C:\temp\githuntdemo\GitHunt-angular2
82 verbose already installed skipping @types/jasmine@^2.2.30 C:\temp\githuntdemo\GitHunt-angular2
83 verbose already installed skipping @types/node@^6.0.38 C:\temp\githuntdemo\GitHunt-angular2
84 verbose already installed skipping angular-cli@1.0.0-beta.11-webpack.8 C:\temp\githuntdemo\GitHunt-angular2
85 verbose already installed skipping codelyzer@~0.0.26 C:\temp\githuntdemo\GitHunt-angular2
86 verbose already installed skipping ts-node@1.2.1 C:\temp\githuntdemo\GitHunt-angular2
87 verbose already installed skipping tslint@3.13.0 C:\temp\githuntdemo\GitHunt-angular2
88 verbose already installed skipping typed-graphql@^1.0.1 C:\temp\githuntdemo\GitHunt-angular2
89 verbose already installed skipping typescript@^2.0.0 C:\temp\githuntdemo\GitHunt-angular2
90 verbose already installed skipping @angular/common@2.0.0 C:\temp\githuntdemo\GitHunt-angular2
91 verbose already installed skipping @angular/compiler@2.0.0 C:\temp\githuntdemo\GitHunt-angular2
92 verbose already installed skipping @angular/core@2.0.0 C:\temp\githuntdemo\GitHunt-angular2
93 verbose already installed skipping @angular/forms@2.0.0 C:\temp\githuntdemo\GitHunt-angular2
94 verbose already installed skipping @angular/http@2.0.0 C:\temp\githuntdemo\GitHunt-angular2
95 verbose already installed skipping @angular/platform-browser@2.0.0 C:\temp\githuntdemo\GitHunt-angular2
96 silly install resolved []
97 info build C:\temp\githuntdemo\GitHunt-angular2
98 info linkStuff githunt@0.0.0
99 silly linkStuff githunt@0.0.0 has C:\temp\githuntdemo as its parent node_modules
100 verbose linkBins githunt@0.0.0
101 verbose linkMans githunt@0.0.0
102 verbose rebuildBundles githunt@0.0.0
103 verbose rebuildBundles [ '.bin',
103 verbose rebuildBundles   '@angular',
103 verbose rebuildBundles   '@types',
103 verbose rebuildBundles   'angular-cli',
103 verbose rebuildBundles   'angular2-apollo',
103 verbose rebuildBundles   'angular2-moment',
103 verbose rebuildBundles   'apollo-client',
103 verbose rebuildBundles   'codelyzer',
103 verbose rebuildBundles   'core-js',
103 verbose rebuildBundles   'node-emoji',
103 verbose rebuildBundles   'rxjs',
103 verbose rebuildBundles   'ts-helpers',
103 verbose rebuildBundles   'ts-node',
103 verbose rebuildBundles   'tslint',
103 verbose rebuildBundles   'typed-graphql',
103 verbose rebuildBundles   'typescript',
103 verbose rebuildBundles   'zone.js' ]
104 info install githunt@0.0.0
105 info postinstall githunt@0.0.0
106 info prepublish githunt@0.0.0
107 verbose validateInstall loading C:\temp\githuntdemo\GitHunt-angular2\package.json for validation
108 verbose stack Error: The package webpack@2.1.0-beta.21 does not satisfy its siblings' peerDependencies requirements
!
108 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:125:32
108 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:268:7
108 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
108 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
108 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
108 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
108 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
108 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
108 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
108 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
109 verbose cwd C:\temp\githuntdemo\GitHunt-angular2
110 error Windows_NT 6.1.7601
111 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall"
112 error node v4.5.0
113 error npm  v2.15.9
114 error code EPEERINVALID
115 error peerinvalid The package webpack@2.1.0-beta.21 does not satisfy its siblings' peerDependencies requirements!
115 error peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
115 error peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
115 error peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
115 error peerinvalid Peer string-replace-loader@1.0.3 wants webpack@1.x.x || 2.x.x
115 error peerinvalid Peer webpack-dev-server@2.1.0-beta.0 wants webpack@^2.1.0-beta
116 verbose exit [ 1, true ]
```

**Comment by bbehling** [comment]
Had to update NPM. After that, now getting a new error on install and trying to run.

Install error:
node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-win32-x64.tar.g
z
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.5.0 (node-v46 ABI) (falling back to sour
ce compile with node-gyp)

C:\temp\githuntdemo\GitHunt-angular2\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Users\mfp4750
0\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (nod
e "" clean )

C:\temp\githuntdemo\GitHunt-angular2\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Users\mfp4750
0\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallba
ck-to-build --module=C:\temp\githuntdemo\GitHunt-angular2\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli
.node --module_name=zopfli --module_path=C:\temp\githuntdemo\GitHunt-angular2\node_modules\node-zopfli\lib\binding\node-
v46-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\temp\githuntdemo\GitHunt-angular2\node_modules\
node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\temp\githuntdemo\GitHunt-an
gular2\node_modules\node-zopfli\lib\binding\node-v46-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\mfp47500\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\con
figure.js:449:14)
gyp ERR! stack     at C:\Users\mfp47500\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:
11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mfp47500\\AppData\\Roaming\\npm\\node_modules\\npm\\n
ode_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\temp\\githuntdemo\\GitHunt-angu
lar2\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:
\\temp\\githuntdemo\\GitHunt-angular2\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64"
gyp ERR! cwd C:\temp\githuntdemo\GitHunt-angular2\node_modules\node-zopfli
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\temp\githuntdem
o\GitHunt-angular2\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_pat
h=C:\temp\githuntdemo\GitHunt-angular2\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\temp\githuntdemo\GitHunt-angular2\node_modules\node-pre-gyp\
lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\temp\\githuntdemo\\GitHunt-angular2\\node_modules\\
node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\temp\githuntdemo\GitHunt-angular2\node_modules\node-zopfli
node-pre-gyp ERR! node -v v4.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\temp\githuntdemo\GitHunt-angular2\node_modules
\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\temp\githuntdemo\GitHunt-a
ngular2\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
githunt@0.0.0 C:\temp\githuntdemo\GitHunt-angular2
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\angular-cli\node_modules\webpack\node_modu
les\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/compiler-cli@0.5.0 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN string-replace-loader@1.0.3 requires a peer of webpack@1.x.x || 2.x.x but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@1.4.0 (node_modules\node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! code 1

Run error:

Error while running script "C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\addon\ng2\models\config\conf
.ts":
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.require.extensions..ts (C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\lib\bootstrap-loca
js:30:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module._load (C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\lib\bootstrap-local.js:55:
)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\addon\ng2\models\config.ts:7:
)
    at Module._compile (module.js:409:26)
Error while running script "C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\addon\ng2\models\config.ts":
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.require.extensions..ts (C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\lib\bootstrap-loca
js:30:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module._load (C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\lib\bootstrap-local.js:55:
)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\addon\ng2\models\config.ts:7:
)
    at Module._compile (module.js:409:26)
Unexpected token ...
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.require.extensions..ts (C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\lib\bootstrap-loca
js:30:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module._load (C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\lib\bootstrap-local.js:55:
)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\temp\githuntdemo\GitHunt-angular2\node_modules\angular-cli\addon\ng2\models\config.ts:7:
)
    at Module._compile (module.js:409:26)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mfp47500\\AppData\\Roaming\\npm\\node_modules\\npm\\bi
\npm-cli.js" "start"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! githunt@0.0.0 start: `ng serve --port 3000 --proxy-config proxy.conf.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the githunt@0.0.0 start script 'ng serve --port 3000 --proxy-config proxy.conf.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the githunt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve --port 3000 --proxy-config proxy.conf.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs githunt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls githunt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp\githuntdemo\GitHunt-angular2\npm-debug.log

**Comment by kamilkisiela** [comment]
@bbehling Try with the latest version. I updated GitHunt to use angular-cli at beta 18th
